name: CodeTesting
channels:
  - conda-forge
  - c4aarch64
  - defaults
dependencies:
  - affine=2.4.0
  - aom=3.9.1
  - appnope=0.1.4
  - asttokens=2.4.1
  - attrs=24.2.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.0
  - aws-c-common=0.10.3
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.1
  - aws-c-io=0.15.2
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.2
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.6
  - aws-sdk-cpp=1.11.449
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - blosc=1.21.6
  - branca=0.7.2
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.3
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - charset-normalizer=3.4.0
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cmcrameri=1.9
  - comm=0.2.2
  - contextily=1.6.2
  - curl=8.10.1
  - cycler=0.12.1
  - dav1d=1.2.1
  - dcw-gmt=2.2.0
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fftw=3.3.10
  - folium=0.18.0
  - freetype=2.12.1
  - freexl=2.0.0
  - geographiclib=2.0
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geopy=2.4.1
  - geos=3.13.0
  - geotiff=1.7.3
  - gflags=2.2.2
  - ghostscript=10.04.0
  - giflib=5.2.2
  - glog=0.7.1
  - gmt=6.5.0
  - gshhg-gmt=2.3.7
  - h2=4.1.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jedi=0.19.2
  - jinja2=3.1.4
  - joblib=1.4.2
  - json-c=0.18
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarchive=3.7.7
  - libarrow=18.1.0
  - libarrow-acero=18.1.0
  - libarrow-dataset=18.1.0
  - libarrow-substrait=18.1.0
  - libavif16=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.10.1
  - libcxx=19.1.4
  - libde265=1.0.15
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgdal-core=3.10.0
  - libgdal-jp2openjpeg=3.10.0
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.82.2
  - libgoogle-cloud=2.31.0
  - libgoogle-cloud-storage=2.31.0
  - libgrpc=1.67.1
  - libheif=1.18.2
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libopenblas=0.3.28
  - libparquet=18.1.0
  - libpng=1.6.44
  - libprotobuf=5.28.2
  - libre2-11=2024.07.02
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.47.0
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.8.0
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=19.1.4
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.8.1
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mercantile=1.2.1
  - minizip=4.0.7
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - openjpeg=2.5.2
  - openssl=3.6.0
  - orc=2.0.3
  - packaging=24.2
  - parso=0.8.4
  - pcre=8.45
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.3.1
  - platformdirs=4.3.6
  - proj=9.5.0
  - prompt-toolkit=3.0.48
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow-core=18.1.0
  - pycparser=2.22
  - pygments=2.18.0
  - pygmt=0.13.0
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.12.7
  - python-dateutil=2.9.0.post0
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytz=2024.1
  - qhull=2020.2
  - rav1e=0.6.6
  - re2=2024.07.02
  - readline=8.2
  - requests=2.32.3
  - rioxarray=0.17.0
  - setuptools=75.6.0
  - six=1.16.0
  - snappy=1.2.1
  - snuggs=1.4.7
  - sqlite=3.47.0
  - stack_data=0.6.2
  - svt-av1=2.3.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024b
  - uriparser=0.9.8
  - urllib3=2.2.3
  - wcwidth=0.2.13
  - wheel=0.45.1
  - x265=3.5
  - xarray=2024.11.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xyzservices=2024.9.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
    - brotli==1.1.0
    - cffi==1.17.1
    - cftime==1.6.4
    - contourpy==1.3.1
    - debugpy==1.8.9
    - fonttools==4.55.0
    - gdal==3.10.0
    - greenlet==3.1.1
    - kiwisolver==1.4.7
    - lxml==5.3.0
    - markupsafe==3.0.2
    - matplotlib==3.9.2
    - netcdf4==1.6.4
    - numpy==1.26.4
    - obspy==1.4.1
    - pandas==2.2.3
    - pillow==11.0.0
    - psutil==6.1.0
    - pyarrow==18.1.0
    - pyogrio==0.10.0
    - pyproj==3.7.0
    - pyzmq==26.2.0
    - rasterio==1.4.2
    - scikit-learn==1.5.2
    - scipy==1.14.1
    - shapely==2.0.6
    - sqlalchemy==1.4.54
    - tornado==6.4.2
    - unicodedata2==15.1.0
    - zstandard==0.23.0
    - cmcrameri
    - gdown
    - librosa
